// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: { evm: string | null; pvm: string | null; evmTreasury: string | null; pvmTreasury: string | null } = {
	evm: "0xecfdf8d9b8253097ba78ba779623873e0dfe5f49",
	pvm: "0x018c94c1f2c00e39644c97d2aaa96e9b33b8a8eb",
	evmTreasury: "0xb0c715f8535B235023d58b5263226F4Ee375a1AA",
	pvmTreasury: "0xcC2cEE8E514E3fD894569710a2D3F671f8589d3c",
};
