// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: {
	evm: string | null;
	pvm: string | null;
	evmTreasury: string | null;
	pvmTreasury: string | null;
} = {
	evm: "0x253028394517e27a6d22233e94b5b53c62926940",
	pvm: "0x018c94c1f2c00e39644c97d2aaa96e9b33b8a8eb",
	evmTreasury: "0xA35C4CF55928afb9b8A4A8aC209Cd966Af230F75",
	pvmTreasury: "0xcC2cEE8E514E3fD894569710a2D3F671f8589d3c",
};
