// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: { evm: string | null; pvm: string | null } = {
	evm: "0xe1f95d1e04c11bbfa5d23365ce202d117d7c157a",
	pvm: "0x4939ac58d2e9c267fd5b784642244483228a290b",
};
