import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";
import { defineChain } from "viem";

const polkadotHubTestnet = defineChain({
	id: 420420417,
	name: "Polkadot Hub TestNet",
	nativeCurrency: { name: "Paseo", symbol: "PAS", decimals: 18 },
	rpcUrls: {
		default: { http: ["https://services.polkadothub-rpc.com/testnet"] },
	},
});

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_CLI_JSON = path.resolve(__dirname, "../../../cli/aperio/deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

type Deployments = {
	evm: string | null;
	pvm: string | null;
	evmTreasury: string | null;
	pvmTreasury: string | null;
};

function updateDeployments(update: Partial<Deployments>) {
	let data: Deployments = {
		evm: null,
		pvm: null,
		evmTreasury: null,
		pvmTreasury: null,
	};
	try {
		data = { ...data, ...JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8")) };
	} catch {
		// File doesn't exist yet
	}
	data = { ...data, ...update };

	// Write JSON (for CLI and other tools)
	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");
	fs.writeFileSync(DEPLOYMENTS_CLI_JSON, JSON.stringify(data, null, 2) + "\n");

	// Write TypeScript (for frontend) — match project formatting (tabs, trailing commas, unquoted keys)
	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: { evm: string | null; pvm: string | null; evmTreasury: string | null; pvmTreasury: string | null } = {
\tevm: ${fmt(data.evm)},
\tpvm: ${fmt(data.pvm)},
\tevmTreasury: ${fmt(data.evmTreasury)},
\tpvmTreasury: ${fmt(data.pvmTreasury)},
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

async function main() {
	console.log("Deploying Aperio (PVM/resolc)...");

	const [walletClient] = await hre.viem.getWalletClients({ chain: polkadotHubTestnet });
	const publicClient = await hre.viem.getPublicClient({ chain: polkadotHubTestnet });
	const artifact = await hre.artifacts.readArtifact("AperioRepositoryRegistry");

	const hash = await walletClient.deployContract({
		abi: artifact.abi,
		bytecode: artifact.bytecode as `0x${string}`,
	});

	const receipt = await publicClient.waitForTransactionReceipt({
		hash,
		timeout: 120_000,
	});

	if (!receipt.contractAddress) {
		throw new Error(`Deploy tx ${hash} did not create a contract`);
	}

	const treasuryAddress = (await publicClient.readContract({
		address: receipt.contractAddress,
		abi: artifact.abi,
		functionName: "treasury",
	})) as `0x${string}`;

	console.log(`PVM AperioRepositoryRegistry deployed to: ${receipt.contractAddress}`);
	console.log(`PVM AperioIncentivesTreasury deployed to: ${treasuryAddress}`);
	updateDeployments({
		pvm: receipt.contractAddress,
		pvmTreasury: treasuryAddress,
	});
	console.log("Updated deployments.json");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
